"""added ip and protocol

Revision ID: 3617d633c275
Revises: ba6df4b27398
Create Date: 2017-05-05 12:38:12.933366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3617d633c275'
down_revision = 'ba6df4b27398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ldap_server', sa.Column('ip', sa.String(length=45), nullable=True))
    op.add_column('ldap_server', sa.Column('protocol', sa.String(length=10), nullable=True))
    with op.batch_alter_table('ldap_server') as batch_op:
        batch_op.drop_column('starttls')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ldap_server', sa.Column('starttls', sa.BOOLEAN(), nullable=True))
    op.drop_column('ldap_server', 'protocol')
    op.drop_column('ldap_server', 'ip')
    # ### end Alembic commands ###
