"""add gluu_server and gluu_version in oxauth server

Revision ID: 991b6da7a0e3
Revises: 3617d633c275
Create Date: 2017-05-20 03:27:57.334648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991b6da7a0e3'
down_revision = '3617d633c275'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oxauth_server', sa.Column('gluu_server', sa.Boolean(), nullable=True, server_default='1'))
    op.add_column('oxauth_server', sa.Column('gluu_version', sa.String(length=10), nullable=True, server_default="3.0.1"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("oxauth_server") as batch_op:
        batch_op.drop_column('gluu_version')
        batch_op.drop_column('gluu_server')
    ### end Alembic commands ###
