"""added the setup flag to ldapserver

Revision ID: a1217610461f
Revises: 991b6da7a0e3
Create Date: 2017-07-13 22:06:00.643396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1217610461f'
down_revision = '991b6da7a0e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ldap_server', sa.Column('setup', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ldap_server") as batch_op:
        batch_op.drop_column('setup')
    # ### end Alembic commands ###
